# 2_MEN_localization_from_merged_data.R
# collects data on mito localization 
# uses extracellular background 

# REQUIRES a saved csv file generated by merge_volocity_cell_bkgd.R 
#    (older version merged files will not work)
# REQUIRES the original filenames to contain info on temp and threshold
# REQUIRES the correct voxel size to be entered below

# TODO: reduce the number of data frames by gradually adding to a single output table


# Setup -----
require(tidyverse)
require(tcltk) # for file choosing
voxel_size <- 0.0011907 #     voxel size is 0.0011907 um3

# Load data ----

df_file <- tk_choose.files(default = "", caption = "Select the merged CSV with cell and background values", multi = FALSE) # file chooser window

# do not use locale = latin1, because the saved CSV is in default encoding (UTF-8). Otherwise special characters in Volume column will not be read properly.

df <- read_csv(df_file,
                     col_types = cols(.default = "d",
                                      filename = "c",
                                      Name = "c",
                                      `Item Name` = "c",
                                      Population = "c",
                                      Type = "c"))

# Summarize mito values -----

  # how to copy/paste the column name with superscript:
  # stupid_names <- colnames(df)
  # stupid_names[7]

# NOTE: It is possible to have Voxel Count as a column, but this is set in global Volocity preferences, and so it might not always be present. Therefore we always calculate voxel count.

all_mito <- df %>% filter(Population == "Mito") %>%
  group_by(filename) # mitos in a cell are grouped

raw_mito_intden <- all_mito %>%
  summarise(RawMitoIntDen = sum(`Sum (roGFP 470 (DCI: 60 its, roGFP 470))`), 
            RawMitoMean = sum(`Mean (roGFP 470 (DCI: 60 its, roGFP 470))`*`Volume (µm³)`)/sum(`Volume (µm³)`),
            MitoVolume_um3 = sum(`Volume (µm³)`),
            ItemName = first(`Item Name`)) 


# Get whole-cell values -------

# Uncorrected cell intden

raw_cell_intden <- df %>% filter(Population == "ROIs") %>% # could be cell and small cellular background ROIs here
  group_by(filename) %>%
  filter(`Volume (µm³)` == max(`Volume (µm³)`)) %>% # take the larger ROI from each file in case there was an intracellular ROI
  select(filename,
         RawCellIntDen = `Sum (roGFP 470 (DCI: 60 its, roGFP 470))`,
         RawCellMean = `Mean (roGFP 470 (DCI: 60 its, roGFP 470))`,
         CellVolume_um3 = `Volume (µm³)`,
         ItemName = `Item Name`,
         ExtracellularBackground = ExtracellularBackground)

# Collect columns for cell, mito, and background ------

cell_mito_xc_bkd <- raw_cell_intden %>% ungroup %>% 
  mutate(
  RawMitoIntDen = raw_mito_intden$RawMitoIntDen,
  RawMitoMean = raw_mito_intden$RawMitoMean,
  MitoVolume_um3 = raw_mito_intden$MitoVolume_um3)



# Background-corr. IntDen -------

#   corr intden = (sum) - (background * voxel count)
#     where voxel count = volume µm3 / voxel size µm3/pixel


bkgcorr <- function (rawmean, 
                     vol,
                     voxsize,
                     background) {
  # subtracts background from every voxel in a volume 
  # uses the mean rather than intden, in order to avoid truncation of sig figs by Volocity 
  (rawmean - background) * (vol/voxsize)
}


cell_corr <- bkgcorr(cell_mito_xc_bkd$RawCellMean,
                     cell_mito_xc_bkd$CellVolume_um3,
                     voxel_size,
                     cell_mito_xc_bkd$ExtracellularBackground)

mito_corr <- bkgcorr(cell_mito_xc_bkd$RawMitoMean,
                     cell_mito_xc_bkd$MitoVolume_um3,
                     voxel_size,
                     cell_mito_xc_bkd$ExtracellularBackground)

# Fraction of green signal in mito ----
# note this is a "cookie-cutter" shape and underestimates the true fraction within the cell

frac_mito <- mito_corr/cell_corr
 
corrected_mito_loc_xc <- cell_mito_xc_bkd %>% mutate(CellIntDenCorr = cell_corr, MitoIntDenCorr = mito_corr, FractionInMito = frac_mito)

# Background-corr. mean GFP in mitos  ------
# mean per cell = (sum/voxel count) - background
mito_mean_corr <- corrected_mito_loc_xc$RawMitoMean - corrected_mito_loc_xc$ExtracellularBackground

corrected_mito_loc_xc <- corrected_mito_loc_xc %>% mutate(MitoMeanCorr = mito_mean_corr)


# Compare results by temperature and threshold offset ------

# extract the threshold offset from the filename 

mito_thresh_exp <- "m([:graph:]+)\\.csv" # any letter/number/punc characters between m and .csv

mito_thresh <- str_match(corrected_mito_loc_xc$filename, mito_thresh_exp)

# extract the temperature from the filename 

temp_exp <- "(\\d{2})C" # any 2 number characters before C

temp <- str_match(corrected_mito_loc_xc$filename, temp_exp)

corrected_mito_loc_xc <- corrected_mito_loc_xc  %>%
  mutate(MitoThresh = mito_thresh[,2]) %>%
  mutate(Temp = temp[,2])

# all data by temp

# remove impossible fractions > 1
corrected_mito_loc_xc_filt <- corrected_mito_loc_xc %>% filter(FractionInMito < 1.0)


# Save csv table ------
# overwrites without warning!

# saves the data one level up 
parentName <- basename(dirname(df_file)) # parent directory without higher levels
parentDir <- dirname(df_file)

outputFile = paste(Sys.Date(), parentName, "_mito_loc.csv") # spaces will be inserted
write_csv(corrected_mito_loc_xc_filt,file.path(parentDir, outputFile))
