# 2a_MEN_localization_from_merged_data.R
# collects data on mito localization 
# uses extracellular background 

# revisions vs original "2": 
# --estimates cytoplasmic level as mean of "cookie cutter" -- best available data if lacking a cytoplasmic background
# -- calculates data for each threshold separately
# -- calculates volume-weighted SD for mitos in a cell. 
# -- user can input original data collection date

# REQUIRES a saved csv file generated by 1_merge_volocity_cell_bkgd.R 
#    (older version merged files will not work)
# REQUIRES the original filenames to contain info on temp and threshold
# REQUIRES the correct voxel size to be entered below

# TODO: reduce the number of data frames by gradually adding to a single output table


# Setup -----
require(tidyverse)
require(tcltk) # for file choosing
voxel_size <- 0.0011907 #     voxel size is 0.0011907 um3

# Load data ----

df_file <- tk_choose.files(default = "", caption = "Select the merged CSV with cell and background values", multi = FALSE) # file chooser window

# do not use locale = latin1, because the saved CSV is in default encoding (UTF-8). Otherwise special characters in Volume column will not be read properly.

df <- read_csv(df_file,
                     col_types = cols(.default = "d",
                                      filename = "c",
                                      Name = "c",
                                      `Item Name` = "c",
                                      Population = "c",
                                      Type = "c"))

# Get original data date

orig_date <- readline("Please enter the original date of this data (YYYY-MM-DD)")

# Summarize mito values by cell -----

  # how to copy/paste the column name with superscript:
  # stupid_names <- colnames(df)
  # stupid_names[7]

# NOTE: It is possible to have Voxel Count as a column, but this is set in global Volocity preferences, and so it might not always be present. Therefore we always calculate voxel count.

# mitos in a cell are grouped

all_mito <- df %>% filter(Population == "Mito") %>%
  group_by(filename) 

# calculate volume-weighted mean and SD

raw_mito_intden <- all_mito %>%
  summarise(RawMitoIntDen = sum(`Sum (roGFP 470 (DCI: 60 its, roGFP 470))`), 
            RawMitoMean = sum(`Mean (roGFP 470 (DCI: 60 its, roGFP 470))`*`Volume (µm³)`)/sum(`Volume (µm³)`),
            MitoVolume_um3 = sum(`Volume (µm³)`),
            RawMitoSD = sum(`Standard Deviation (roGFP 470 (DCI: 60 its, roGFP 470))`*`Volume (µm³)`)/sum(`Volume (µm³)`),
            ItemName = first(`Item Name`)) 


# Get background and cell ROI values -------

# could be cell and small cellular background ROIs here
# take the larger ROI from each file in case there was an intracellular ROI

# ESTIMATE cytoplasmic level as mean of whole-cell ROI


raw_cell_intden <- df %>% filter(Population == "ROIs") %>% 
  group_by(filename) %>%
  filter(`Volume (µm³)` == max(`Volume (µm³)`)) %>% 
  select(filename,
         ItemName = `Item Name`,
         CellMin = `Min (roGFP 470 (DCI: 60 its, roGFP 470))`,
         CellMean = `Mean (roGFP 470 (DCI: 60 its, roGFP 470))`,
         CellSD = `Standard Deviation (roGFP 470 (DCI: 60 its, roGFP 470))`,
         ExtracellularBackground = ExtracellularBackground)


# Collect columns for cell, mito, and background ------

cell_mito_xc_bkd <- raw_cell_intden %>% ungroup %>% 
  mutate(
    RawMitoMean = raw_mito_intden$RawMitoMean,
    MitoVolume_um3 = raw_mito_intden$MitoVolume_um3,
    RawMitoSD = raw_mito_intden$RawMitoSD)


# Background-corr. mean GFP in mitos  ------
# mean per cell = (sum/voxel count) - background
mito_mean_corr <- cell_mito_xc_bkd$RawMitoMean - cell_mito_xc_bkd$ExtracellularBackground

corrected_mito_loc_xc <- cell_mito_xc_bkd %>% 
  mutate(MitoMeanCorr = mito_mean_corr)

# Background-corr. mean GFP in cyto ------
cyto_corr <- corrected_mito_loc_xc$CellMean - corrected_mito_loc_xc$ExtracellularBackground

corrected_mito_loc_xc <- corrected_mito_loc_xc %>% 
  mutate(CellMeanCorr = cyto_corr)

# Calculate mito localization as (corrected for xc bkgd) ----
# mito / cyto 

mito_loc <- corrected_mito_loc_xc$MitoMeanCorr / corrected_mito_loc_xc$CellMeanCorr

corrected_mito_loc_xc <- corrected_mito_loc_xc %>% 
  mutate(MitoLoc = mito_loc)


# Extract data from consistently named files  ------

# extract the threshold offset from the filename 

mito_thresh_exp <- "m([:graph:]+)\\.csv" # any letter/number/punc characters between m and .csv

mito_thresh <- str_match(corrected_mito_loc_xc$filename, mito_thresh_exp)

# extract the temperature from the filename 

temp_exp <- "(\\d{2})C" # any 2 number characters before C

temp <- str_match(corrected_mito_loc_xc$filename, temp_exp)

corrected_mito_loc_xc <- corrected_mito_loc_xc  %>%
  mutate(MitoThresh = mito_thresh[,2]) %>%
  mutate(Temp = temp[,2])

# Save csv table ------
# overwrites without warning!

# saves the data one level up 
parentName <- basename(dirname(df_file)) # parent directory without higher levels
parentDir <- dirname(df_file)

outputFile = paste(Sys.Date(), orig_date, parentName, "_mito_loc.csv") # spaces will be inserted
write_csv(corrected_mito_loc_xc,file.path(parentDir, outputFile))
