# 3_MEN_analysis.R
# analyzes data on mito localization expts
# uses extracellular background


# REQUIRES a saved csv file generated by 2_MEN_localization_from_merged_data.R


# TODO: Add n to the labels for the plots (for each group)

# Setup -----
require(tidyverse)
require(tcltk) # for file choosing

# Load data ----

df_file <- tk_choose.files(default = "", caption = "Select the CSV with mito localization", multi = FALSE) # file chooser window

# do not use locale = latin1, because the saved CSV is in default encoding (UTF-8). Otherwise special characters in Volume column will not be read properly.

corrected_mito_loc_xc_filt <- read_csv(df_file,
                     col_types = cols(.default = "d",
                                      filename = "c",
                                      ItemName = "c"))


# Compare results by temperature and threshold offset ------


# plots ----
# TODO: also plot jittered scatter with alpha for better visualization of outliers vs main bulk of measurements


boxplot(corrected_mito_loc_xc_filt$FractionInMito ~ corrected_mito_loc_xc_filt$Temp, main = "Fraction of GFP integrated density in mitochondria") # whiskers extend to 1.5x interquartile range

boxplot(corrected_mito_loc_xc_filt$MitoMeanCorr ~ corrected_mito_loc_xc_filt$Temp, main = "Mean GFP intensity in mitochondria")

# Compare total cell GFP across temperatures

# is total cellular GFP constant with temp?
boxplot(corrected_mito_loc_xc_filt$CellIntDenCorr ~ corrected_mito_loc_xc_filt$Temp, main = "Total corrected cell GFP")

# cell intden vs volume
# plot(corrected_mito_loc_xc$CellIntDenCorr, corrected_mito_loc_xc$CellVolume_um3, main = "XC Bkgd")

boxplot(corrected_mito_loc_xc_filt$FractionInMito ~ corrected_mito_loc_xc_filt$MitoThresh, main = "Fraction of MEN in mito, by threshold offset")

# Statistical tests -----

permTfrac <- corrected_mito_loc_xc_filt %>% 
  filter(Temp == 25) %>% 
  select(FractionInMito) %>%
  unlist

restrTfrac <- corrected_mito_loc_xc_filt %>% 
  filter(Temp == 36) %>% 
  select(FractionInMito) %>%
  unlist

permTmean <- corrected_mito_loc_xc_filt %>% 
  filter(Temp == 25) %>% 
  select(MitoMeanCorr) %>%
  unlist

restrTmean <- corrected_mito_loc_xc_filt %>% 
  filter(Temp == 36) %>% 
  select(MitoMeanCorr) %>%
  unlist

# are data normally distributed?

hist(permTfrac)
qqnorm(permTfrac, main = "Fraction of MEN in mito, 25C")
qqline(permTfrac, main = "Fraction of MEN in mito, 25C")
permTfrac_shapiro <- shapiro.test(permTfrac)$p.value # low p value (< 0.05 by convention) means not normal

hist(restrTfrac)
qqnorm(restrTfrac, main = "Fraction of MEN in mito, 36C")
qqline(restrTfrac, main = "Fraction of MEN in mito, 36C")
restrTfrac_shapiro <- shapiro.test(restrTfrac)$p.value

hist(permTmean)
qqnorm(permTmean, main = "Mean of MEN in mito, 25C")
qqline(permTmean, main = "Mean of MEN in mito, 25C")
permTmean_shapiro <- shapiro.test(permTmean)$p.value

hist(restrTmean, breaks = 50)
qqnorm(restrTmean, main = "Mean of MEN in mito, 36C")
qqline(restrTmean, main = "Mean of MEN in mito, 36C")
restrTmean_shapiro <- shapiro.test(restrTmean)$p.value

# # comparison with true normal data
# testdata <- rnorm(1000)
# hist(testdata)
# qqnorm(testdata)
# qqline(testdata)
# testdata_shapiro <- shapiro.test(testdata)$p.value

# wilcoxon_frac <- wilcox.test(permTfrac, restrTfrac)$p.value
# wilcoxon_mean <- wilcox.test(permTmean, restrTmean)$p.value
# 
# # sample means and SEM
# mean_25_frac <- mean(permTfrac)
# mean_36_frac <- mean(restrTfrac)
# mean_25_mean <- mean(permTmean)
# mean_36_mean <- mean(restrTmean)
# 
# se <- function(x) sqrt(var(x)/length(x))
# se_25_frac <- se(permTfrac)
# se_36_frac <- se(restrTfrac)
# se_25_mean <- se(permTmean)
# se_36_mean <- se(restrTmean)

#TODO: collect statistics and save
# TODO: Express mito frac as fold change vs perm temp.  

# do not use t-test for non-normally distributed data
# frac_t <- t.test(permTfrac, restrTfrac)
# mean_t <- t.test(permTmean, restrTmean)

# Save csv table ------
# overwrites without warning!

# saves the data one level up 
#parentName <- basename(dirname(df_file)) # parent directory without higher levels
#parentDir <- dirname(df_file)

#outputFile = paste(Sys.Date(), parentName, "mito_loc.csv") # spaces will be inserted
#write_csv(corrected_mito_loc_xc_filt,file.path(parentDir, outputFile))

