# 3a_MEN_analysis_from_merged_data.R
# analyzes data on mito localization expts
# uses extracellular background

# REQUIRES a saved csv file generated by 2_MEN_localization_from_merged_data.R


# revisions vs original "3": 
# --uses cytoplasmic level as mean of "cookie cutter" -- best available data if lacking a cytoplasmic background
# -- calculates results for each threshold separately
# -- calculates a possible metric for threshold quality: volume-weighted SD/mean for mitos in a cell. This should be high if mitos are overthresholded. In 3 datasets of difft proteins, genotypes, dates, and temps, most values are < 0.3 and almost all are < 0.4.
# -- user can input original data collection date


# TODO: Add n to the labels for the plots (for each group)

# Setup -----
require(tidyverse)
require(tcltk) # for file choosing

# Load data ----

df_file <- tk_choose.files(default = "", caption = "Select the CSV with mito localization", multi = FALSE) # file chooser window

# do not use locale = latin1, because the saved CSV is in default encoding (UTF-8). Otherwise special characters in Volume column will not be read properly.

corrected_mito_loc_xc <- read_csv(df_file,
                     col_types = cols(.default = "d",
                                      filename = "c",
                                      filename1 = "c",
                                      ItemName = "c"))


corrected_mito_loc_xc <- corrected_mito_loc_xc %>% filter(is.na(MitoLoc) == FALSE)


# Get original data date and strain

orig_date <- readline("Please enter the original date of this data (YYYY-MM-DD):")
strain <- readline("Please enter the strain name:")

# Take cells from a particular threshold offset ------


corrected_mito_loc_xc_25 <- corrected_mito_loc_xc %>%
  filter(MitoThresh == "-25")
o25_perm <- filter(corrected_mito_loc_xc_25, Temp == "25")
o25_restr <- filter(corrected_mito_loc_xc_25, Temp == "36")

corrected_mito_loc_xc_35 <- corrected_mito_loc_xc %>%
  filter(MitoThresh == "-35")
o35_perm <- filter(corrected_mito_loc_xc_35, Temp == "25")
o35_restr <- filter(corrected_mito_loc_xc_35, Temp == "36")

corrected_mito_loc_xc_50 <- corrected_mito_loc_xc %>%
  filter(MitoThresh == "-50")
o50_perm <- filter(corrected_mito_loc_xc_50, Temp == "25")
o50_restr <- filter(corrected_mito_loc_xc_50, Temp == "36")


# Optional -- filter by sd/mean < 0.4 or 0.3

corrected_mito_loc_xc_25filt <- corrected_mito_loc_xc %>%
  filter(MitoThresh == "-25") %>%
  filter(RawMitoSD/RawMitoMean < 0.3)
o25_permfilt <- filter(corrected_mito_loc_xc_25filt, Temp == "25")
o25_restrfilt <- filter(corrected_mito_loc_xc_25filt, Temp == "36")

corrected_mito_loc_xc_35filt <- corrected_mito_loc_xc %>%
  filter(MitoThresh == "-35") %>%
  filter(RawMitoSD/RawMitoMean < 0.3)
o35_permfilt <- filter(corrected_mito_loc_xc_35filt, Temp == "25")
o35_restrfilt <- filter(corrected_mito_loc_xc_35filt, Temp == "36")

corrected_mito_loc_xc_50filt <- corrected_mito_loc_xc %>%
  filter(MitoThresh == "-50")%>%
  filter(RawMitoSD/RawMitoMean < 0.3)
o50_permfilt <- filter(corrected_mito_loc_xc_50filt, Temp == "25")
o50_restrfilt <- filter(corrected_mito_loc_xc_50filt, Temp == "36")


# Compare 25 to 36 for each threshold offset  ----

# Mito localization measure -- Statistics -----


foldchange_25filt <- mean(o25_restrfilt$MitoLoc)/mean(o25_permfilt$MitoLoc)
foldchange_25 <- mean(o25_restr$MitoLoc)/mean(o25_perm$MitoLoc)

wilcoxon_25filt <- wilcox.test(MitoLoc ~ Temp, data = corrected_mito_loc_xc_25filt)$p.value
wilcoxon_25 <- wilcox.test(MitoLoc ~ Temp, data = corrected_mito_loc_xc_25)$p.value

foldchange_35filt <- mean(o35_restrfilt$MitoLoc)/mean(o35_permfilt$MitoLoc)
foldchange_35 <- mean(o35_restr$MitoLoc)/mean(o35_perm$MitoLoc)

wilcoxon_35filt <- wilcox.test(MitoLoc ~ Temp, data = corrected_mito_loc_xc_35filt)$p.value
wilcoxon_35 <- wilcox.test(MitoLoc ~ Temp, data = corrected_mito_loc_xc_35)$p.value

foldchange_50filt <- mean(o50_restrfilt$MitoLoc)/mean(o50_permfilt$MitoLoc)
foldchange_50 <- mean(o50_restr$MitoLoc)/mean(o50_perm$MitoLoc)

wilcoxon_50filt <- wilcox.test(MitoLoc ~ Temp, data = corrected_mito_loc_xc_50filt)$p.value
wilcoxon_50 <- wilcox.test(MitoLoc ~ Temp, data = corrected_mito_loc_xc_50)$p.value


# Plots ------

# TODO: maybe also plot violin or jittered scatter with alpha for better visualization of outliers vs main bulk of measurements

# boxplot(corrected_mito_loc_xc_25$MitoLoc ~ corrected_mito_loc_xc_25$Temp, main = "Mitochondrial localization (mito mean/cell mean), offset -25, SD/mean < 0.3") # whiskers extend to 1.5x interquartile range
# 

plot25 <- ggplot(corrected_mito_loc_xc_25, aes(factor(Temp), MitoLoc)) +
  geom_boxplot(color = "black", fill = "blue", alpha = 0.5) +
  scale_y_continuous(limits=c(0,8)) +
  labs(title =  paste("Mitochondrial Localization,", strain),
       x = "Temperature", y = "Mito Mean / Cell Mean") +
  theme_bw() +
  theme(text = element_text(size=18), plot.title = element_text(size = 14, face="bold"))
# 
# plot35 <- ggplot(corrected_mito_loc_xc_35, aes(factor(Temp), MitoLoc)) +
#   geom_boxplot(color = "black", fill = "grey75") +
#   labs(title =  paste("Mitochondrial Localization,", strain, ", offset -35"),
#        x = "Temperature", y = "Mito Mean / Cell Mean") +
#   theme_bw()+
#   theme(text = element_text(size=18))
# 
# plot50 <- ggplot(corrected_mito_loc_xc_50, aes(factor(Temp), MitoLoc)) +
#   geom_boxplot(color = "black", fill = "grey75") +
#   labs(title =  paste("Mitochondrial Localization,", strain, ", offset -50"),
#        x = "Temperature", y = "Mito Mean / Cell Mean") +
#   theme_bw()+
#   theme(text = element_text(size=18))
# 
# plot25filt <- ggplot(corrected_mito_loc_xc_25filt, aes(factor(Temp), MitoLoc)) +
#   geom_boxplot(color = "black", fill = "blue", alpha = 0.5) +
#   scale_y_continuous(limits=c(0,8)) +
#   labs(title =  paste("Mitochondrial Localization,", strain),
#        x = "Temperature", y = "Mito Mean / Cell Mean") +
#   theme_bw() +
#   theme(text = element_text(size=18), plot.title = element_text(size = 14, face="bold"))
# 
# plot35filt <- ggplot(corrected_mito_loc_xc_35filt, aes(factor(Temp), MitoLoc)) +
#   geom_boxplot(color = "black", fill = "grey75") +
#   labs(title =  paste("Mitochondrial Localization,", strain, ", offset -35, SD/mean < 0.3"),
#        x = "Temperature", y = "Mito Mean / Cell Mean") +
#   theme_bw()+
#   theme(text = element_text(size=18))
# 
# plot50filt <- ggplot(corrected_mito_loc_xc_50filt, aes(factor(Temp), MitoLoc)) +
#   geom_boxplot(color = "black", fill = "grey75") +
#   labs(title =  paste("Mitochondrial Localization,", strain, ", offset -50, SD/mean < 0.3"),
#        x = "Temperature", y = "Mito Mean / Cell Mean") +
#   theme_bw()+
#   theme(text = element_text(size=18))

# Absolute mean in mito
# 
# boxplot(corrected_mito_loc_xc_25$MitoMeanCorr ~ corrected_mito_loc_xc_25$Temp, main = "Mean GFP intensity in mitochondria, offset -25, SD/mean < 0.3")
# 
# boxplot(corrected_mito_loc_xc_35$MitoMeanCorr ~ corrected_mito_loc_xc_35$Temp, main = "Mean GFP intensity in mitochondria, offset -35, SD/mean < 0.3")
# 
# boxplot(corrected_mito_loc_xc_50$MitoMeanCorr ~ corrected_mito_loc_xc_50$Temp, main = "Mean GFP intensity in mitochondria, offset -50, SD/mean < 0.3")

# saves the data in the same directory
parentDir <- dirname(df_file)
# parentName <- basename(dirname(df_file)) # parent directory without higher levels

# TODO: Save n, fold change, wilcoxon p
# 
ggsave(plot = plot25, filename = file.path(parentDir, paste(Sys.Date(), strain, "offset -25.png")))
# ggsave(plot = plot35, filename = file.path(parentDir, paste(Sys.Date(), strain, "offset -35.png")))
# ggsave(plot = plot50, filename = file.path(parentDir, paste(Sys.Date(), strain, "offset -50.png")))


# ggsave(plot = plot25filt, filename = file.path(parentDir, paste(Sys.Date(), strain, "offset -25 SD filt.png")))
# ggsave(plot = plot35filt, filename = file.path(parentDir, paste(Sys.Date(), strain, "offset -35 SD filt.png")))
# ggsave(plot = plot50filt, filename = file.path(parentDir, paste(Sys.Date(), strain, "offset -50 SD filt.png")))


# TODO: write csvs of the filtered data for each temp
